// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using hastaneRandevuSistemi.Models.patientsModel;

#nullable disable

namespace hastaneRandevuSistemi.Migrations.Patients
{
    [DbContext(typeof(PatientsContext))]
    [Migration("20230802151118_Patient")]
    partial class Patient
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("hastaneRandevuSistemi.Models.patientsModel.patients", b =>
                {
                    b.Property<int>("patId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("patId"));

                    b.Property<DateTime>("patBirthday")
                        .HasColumnType("datetime2");

                    b.Property<string>("patCity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("patEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("patName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("patParola")
                        .HasColumnType("int");

                    b.Property<int>("patPhoneNo")
                        .HasColumnType("int");

                    b.Property<string>("patSurname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("patTeParola")
                        .HasColumnType("int");

                    b.HasKey("patId");

                    b.ToTable("Hastalar");
                });
#pragma warning restore 612, 618
        }
    }
}
