// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using hastaneRandevuSistemi.Models.policlinic;

#nullable disable

namespace hastaneRandevuSistemi.Migrations.Policlinic
{
    [DbContext(typeof(PoliclinicContext))]
    partial class PoliclinicContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("hastaneRandevuSistemi.Models.policlinic.policlinic", b =>
                {
                    b.Property<int>("policlinicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("policlinicId"));

                    b.Property<string>("policlinicName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("policlinicNo")
                        .HasColumnType("int");

                    b.HasKey("policlinicId");

                    b.ToTable("Poliklinikler");
                });
#pragma warning restore 612, 618
        }
    }
}
